### PR TITLE
refactor 2

### PR DESCRIPTION
**Pull request by ilyida**
when u know it doesnt crash u can accept this pull req

### CODE REVIEW

**Comment by ilyida** [comment]
When is it crashing? Also I am not adding any code to this project, only refactoring existing code to be easier to read and cleaner.

**Comment by RetracedFn** [comment]
i inj and after like 4 seconds crash almost insta

**Comment by ilyida** [comment]
whats ur discord

**Comment by RetracedFn** [comment]
dont have discord

**Pull request closed without merging**
